---
name: Workflow - Push

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  linters:
    name: Run linters
    uses: ./.github/workflows/linters.yml

  rust_build:
    name: Build Rust project
    uses: ./.github/workflows/rust-build.yml

  linters_cargo:
    name: Run Cargo linters
    uses: ./.github/workflows/linters-cargo.yml
    needs: rust_build

  # benchmark:
  #   name: Run benchmarks
  #   uses: ./.github/workflows/benchmarks.yml
  #   needs: [rust_build, tests]
  #   permissions:
  #     # deployments permission to deploy GitHub pages website
  #     deployments: write
  #     # contents permission to update benchmark contents in gh-pages branch
  #     contents: write
  #     # post on the pull-request page
  #     pull-requests: write

  # TODO change it to benchmark when enabled
  rustdoc:
    name: Deploy docs to GitHub Pages
    uses: ./.github/workflows/rustdoc.yml
    needs: linters_cargo
    permissions:
      contents: write
